### ISSUE TITLE
Crash when download

### ISSUE THREAD

**Issue by tenshi0xx** [Lost-MSth/Arcaea-Bundler#1]
Hi, the game crash when downloading bundle creating by this tool, only armeabi have this problem, can you check?

**Comment by Lost-MSth** [comment]
Show me your JSON metadata.

**Comment by tenshi0xx** [comment]
> Show me your JSON metadata.
{"versionNumber": "1.0", "previousVersionNumber": null, "applicationVersionNumber": "5.3.1", "uuid": "9e2bded2e", "removed": [], "added": [{"path": "packlist", "byteOffset": 0, "length": 58748, "sha256HashBase64Encoded": "zuz/D6OOAraLcg11yRYF0cqQMvmj6kSjosnI8f6uPBI="}, {"path": "songlist", "byteOffset": 58748, "length": 726105, "sha256HashBase64Encoded": "8kDHIhD8xBnu6kV0ZAfnbnS+/QC9N4w0a/xbbzEUNP8="}, {"path": "unlocks", "byteOffset": 784853, "length": 91802, "sha256HashBase64Encoded": "MOoPOQMHulSn6JNSju/ddEjeSs0P/nHeABO2PmAKE0I="}, {"path": "alephzero/0.aff", "byteOffset": 876655, "length": 11080, "sha256HashBase64Encoded": "zjoY1Gl8xCMo8a2yfcrcKr/o7ITYW9al91qXA2QK0Jk="}, {"path": "alephzero/1.aff", "byteOffset": 887735, "length": 29488, "sha256HashBase64Encoded": "TUNfLkS2FBHkpX1QibvPdD+0coLHtLmYPJRZbkFU4zI="}, {"path": "alephzero/2.aff", "byteOffset": 917223, "length": 61334, "sha256HashBase64Encoded": "wDo1OP2JgvTUI5oxVB6tErgLLsjyWBNj5I3XvQ2JDi4="}, {"path": "alephzero/base.ogg", "byteOffset": 978557, "length": 3407255, "sha256HashBase64Encoded": "E5xdFmxQc2bMZLIGQ1bEeH6MiN3Xn2B8kIXyCMmE/As="}, {"path": "innocence/0.aff", "byteOffset": 4385812, "length": 9633, "sha256HashBase64Encoded": "EFpLPDahy5ITotOhZXYGP+KHVjQrJhEMLz7ev2xWns4="}, {"path": "innocence/1.aff", "byteOffset": 4395445, "length": 16466, "sha256HashBase64Encoded": "0eEX8BEffxyeyFSVSdUZh0cMN8bk2gAC9H/jhYK09+8="}, {"path": "innocence/2.aff", "byteOffset": 4411911, "length": 21997, "sha256HashBase64Encoded": "JfXgPIUHvtiatMMgjlJSWeZpJAu+skkSAg7qRLf9k7Q="}, {"path": "innocence/4.aff", "byteOffset": 4433908, "length": 33280, "sha256HashBase64Encoded": "3r9Oytqn8jYQCIanhWL4EV+3jISJtiiuGMt+wUZyIrQ="}, {"path": "innocence/base.ogg", "byteOffset": 4467188, "length": 3833421, "sha256HashBase64Encoded": "8e7BWsf0q/6ZTZRgrM6vhDy5f9cEKKU7LbjglsBriEQ="}, {"path": "ionostream/0.aff", "byteOffset": 8300609, "length": 7945, "sha256HashBase64Encoded": "4OZU2aqGquQKzpXitSQ24oDcOSAWhFF+owpjRYGVBX8="}, {"path": "ionostream/1.aff", "byteOffset": 8308554, "length": 11468, "sha256HashBase64Encoded": "5SPMjJ9RjhQ/ud62uOGENU6RwjQfCccrGQWI2S8/HqI="}, {"path": "ionostream/2.aff", "byteOffset": 8320022, "length": 37768, "sha256HashBase64Encoded": "RyVbRcggq5aS6o7YYZvoT3Vkg/OWe6AAsfe2olST/DE="}, {"path": "ionostream/4.aff", "byteOffset": 8357790, "length": 38504, "sha256HashBase64Encoded": "l3RpK/200uBlBTiSKHhZ9QlFnuT6Fr9RXZFrgIKl2WM="}, {"path": "ionostream/base.ogg", "byteOffset": 8396294, "length": 3205434, "sha256HashBase64Encoded": "GujG63388pVWFAiH0Av9ms0TfnH+i++3CosPspy4oDQ="}, {"path": "kyorenromance/0.aff", "byteOffset": 11601728, "length": 12257, "sha256HashBase64Encoded": "lWgF+JTMVx3eReGGa3iSgjzd0mS3XOn6ChmrNkjAnoM="}, {"path": "kyorenromance/1.aff", "byteOffset": 11613985, "length": 23026, "sha256HashBase64Encoded": "TEsdNLGFuZZD7IFp8TpEi8aye4/5QmulmRVfp/HTqWo="}, {"path": "kyorenromance/2.aff", "byteOffset": 11637011, "length": 150199, "sha256HashBase64Encoded": "Uuke5RKe9BSq75Dt0c0M9D2L2Uk3tcVoRfjQIr2fV7E="}, {"path": "kyorenromance/base.ogg", "byteOffset": 11787210, "length": 3892343, "sha256HashBase64Encoded": "Q2aFie+rRWme2lAvUpYnB3zgw6M/h15d51F1OmAAc20="}, {"path": "masqueradelegion/0.aff", "byteOffset": 15679553, "length": 13540, "sha256HashBase64Encoded": "UVFBBXeHrUYcsLngOUnSg79xxWzxifrTBLBoIuUJo74="}, {"path": "masqueradelegion/1.aff", "byteOffset": 15693093, "length": 19791, "sha256HashBase64Encoded": "5uSH0hXUcyLS9bv27NyJ6k1MSt1YaOqjWLj6V8f1/IA="}, {"path": "masqueradelegion/2.aff", "byteOffset": 15712884, "length": 45353, "sha256HashBase64Encoded": "TGQfK6ztpkj7/IoXgypO6GPLCdUrARHj/k5oiRfuwM0="}, {"path": "masqueradelegion/base.ogg", "byteOffset": 15758237, "length": 3527240, "sha256HashBase64Encoded": "YkymvVooxsoqk3IiqH7sM0CQieVBfkNUAly/ehm7JM8="}, {"path": "qovat/0.aff", "byteOffset": 19285477, "length": 13379, "sha256HashBase64Encoded": "nX8O0Z2N01wSoeA8b6zQmWQzlWDOt217TzrvjU5ls4w="}, {"path": "qovat/1.aff", "byteOffset": 19298856, "length": 27118, "sha256HashBase64Encoded": "4JLekN8TPf+UJ2m+X5O4wYeHu7WUyEt9NQVyEETKgM0="}, {"path": "qovat/2.aff", "byteOffset": 19325974, "length": 61205, "sha256HashBase64Encoded": "7BB9pKD7fsKo/CCtWo/WYnCFmLlSzoQpJmE1mpuzmZQ="}, {"path": "qovat/base.ogg", "byteOffset": 19387179, "length": 3916131, "sha256HashBase64Encoded": "M0BA+OSjsDGa53n30NQQYCdKBUzWZP3CLU+rYg0h2uo="}, {"path": "suomi/0.aff", "byteOffset": 23303310, "length": 6726, "sha256HashBase64Encoded": "4FqxJRojIIpwr2Ra/c8lObPXbKutMQBbaOtzRbpHEDQ="}, {"path": "suomi/1.aff", "byteOffset": 23310036, "length": 10382, "sha256HashBase64Encoded": "6y+p8PBsVlCFcBa1M2OlN2OmBgKes/yrMF1dBOKjsC8="}, {"path": "suomi/2.aff", "byteOffset": 23320418, "length": 32344, "sha256HashBase64Encoded": "Wov+rgucCPPoImUoJnfnx9Dby+Zn7QVNcKBaRG5gFZ0="}, {"path": "suomi/4.aff", "byteOffset": 23352762, "length": 41113, "sha256HashBase64Encoded": "2OnO3TtGtPHlcf2+wEny/JJQXS3kH3DcUwxqsfL2eys="}, {"path": "suomi/base.ogg", "byteOffset": 23393875, "length": 3125992, "sha256HashBase64Encoded": "7uQJ0CLChwGHbnmj6Z3uTsYPhraoJ8blLBF317idvHs="}], "pathToHash": {"packlist": "zuz/D6OOAraLcg11yRYF0cqQMvmj6kSjosnI8f6uPBI=", "songlist": "8kDHIhD8xBnu6kV0ZAfnbnS+/QC9N4w0a/xbbzEUNP8=", "unlocks": "MOoPOQMHulSn6JNSju/ddEjeSs0P/nHeABO2PmAKE0I=", "alephzero/0.aff": "zjoY1Gl8xCMo8a2yfcrcKr/o7ITYW9al91qXA2QK0Jk=", "alephzero/1.aff": "TUNfLkS2FBHkpX1QibvPdD+0coLHtLmYPJRZbkFU4zI=", "alephzero/2.aff": "wDo1OP2JgvTUI5oxVB6tErgLLsjyWBNj5I3XvQ2JDi4=", "alephzero/base.ogg": "E5xdFmxQc2bMZLIGQ1bEeH6MiN3Xn2B8kIXyCMmE/As=", "innocence/0.aff": "EFpLPDahy5ITotOhZXYGP+KHVjQrJhEMLz7ev2xWns4=", "innocence/1.aff": "0eEX8BEffxyeyFSVSdUZh0cMN8bk2gAC9H/jhYK09+8=", "innocence/2.aff": "JfXgPIUHvtiatMMgjlJSWeZpJAu+skkSAg7qRLf9k7Q=", "innocence/4.aff": "3r9Oytqn8jYQCIanhWL4EV+3jISJtiiuGMt+wUZyIrQ=", "innocence/base.ogg": "8e7BWsf0q/6ZTZRgrM6vhDy5f9cEKKU7LbjglsBriEQ=", "ionostream/0.aff": "4OZU2aqGquQKzpXitSQ24oDcOSAWhFF+owpjRYGVBX8=", "ionostream/1.aff": "5SPMjJ9RjhQ/ud62uOGENU6RwjQfCccrGQWI2S8/HqI=", "ionostream/2.aff": "RyVbRcggq5aS6o7YYZvoT3Vkg/OWe6AAsfe2olST/DE=", "ionostream/4.aff": "l3RpK/200uBlBTiSKHhZ9QlFnuT6Fr9RXZFrgIKl2WM=", "ionostream/base.ogg": "GujG63388pVWFAiH0Av9ms0TfnH+i++3CosPspy4oDQ=", "kyorenromance/0.aff": "lWgF+JTMVx3eReGGa3iSgjzd0mS3XOn6ChmrNkjAnoM=", "kyorenromance/1.aff": "TEsdNLGFuZZD7IFp8TpEi8aye4/5QmulmRVfp/HTqWo=", "kyorenromance/2.aff": "Uuke5RKe9BSq75Dt0c0M9D2L2Uk3tcVoRfjQIr2fV7E=", "kyorenromance/base.ogg": "Q2aFie+rRWme2lAvUpYnB3zgw6M/h15d51F1OmAAc20=", "masqueradelegion/0.aff": "UVFBBXeHrUYcsLngOUnSg79xxWzxifrTBLBoIuUJo74=", "masqueradelegion/1.aff": "5uSH0hXUcyLS9bv27NyJ6k1MSt1YaOqjWLj6V8f1/IA=", "masqueradelegion/2.aff": "TGQfK6ztpkj7/IoXgypO6GPLCdUrARHj/k5oiRfuwM0=", "masqueradelegion/base.ogg": "YkymvVooxsoqk3IiqH7sM0CQieVBfkNUAly/ehm7JM8=", "qovat/0.aff": "nX8O0Z2N01wSoeA8b6zQmWQzlWDOt217TzrvjU5ls4w=", "qovat/1.aff": "4JLekN8TPf+UJ2m+X5O4wYeHu7WUyEt9NQVyEETKgM0=", "qovat/2.aff": "7BB9pKD7fsKo/CCtWo/WYnCFmLlSzoQpJmE1mpuzmZQ=", "qovat/base.ogg": "M0BA+OSjsDGa53n30NQQYCdKBUzWZP3CLU+rYg0h2uo=", "suomi/0.aff": "4FqxJRojIIpwr2Ra/c8lObPXbKutMQBbaOtzRbpHEDQ=", "suomi/1.aff": "6y+p8PBsVlCFcBa1M2OlN2OmBgKes/yrMF1dBOKjsC8=", "suomi/2.aff": "Wov+rgucCPPoImUoJnfnx9Dby+Zn7QVNcKBaRG5gFZ0=", "suomi/4.aff": "2OnO3TtGtPHlcf2+wEny/JJQXS3kH3DcUwxqsfL2eys=", "suomi/base.ogg": "7uQJ0CLChwGHbnmj6Z3uTsYPhraoJ8blLBF317idvHs="}, "pathToDetails": {"songs/unlocks": null, "songs/packlist": null, "songs/songlist": null}}

**Comment by Lost-MSth** [comment]
See README carefully:
```md
Bundle folder is equal to assets, which must include songs/songlist, songs/packlist and songs/unlocks.
```

**Comment by tenshi0xx** [comment]
> See README carefully:
> 
> ```
> Bundle folder is equal to assets, which must include songs/songlist, songs/packlist and songs/unlocks.
> ```

![image](https://github.com/Lost-MSth/Arcaea-Bundler/assets/156825971/a0383bb4-3928-457d-88b1-c51a468beccd)

**Comment by Lost-MSth** [comment]
No, no. They should be in the `songs` folder
`assets` folder's structure can be checked in any APK before.

```
assets
- char
- songs
  - songlist
  - dl_drg
    - preview.ogg
    - ...
  - ...
- ...
```

**Comment by tenshi0xx** [comment]
> No, no. They should be in the `songs` folder `assets` folder's structure can be checked in any APK before.

can you check your discord?
